apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
        - name: content-api
          image: 276020727502.dkr.ecr.us-east-2.amazonaws.com/content:12
          env:
            - name: NODE_ENV
              value: production
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-username-secret
                  key: DB_USERNAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host-secret
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database-secret
                  key: DB_DATABASE
          ports:
            - containerPort: 3000
