on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged_and_specific_message:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged and contains the specific message
