on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged and the commit message contains the specific message
