on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $commit_message != *"build"* ]]; then
            echo "Commit message does not contain the specific text. Exiting."
            exit 0
          fi
          echo The PR was merged
