name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from GITHUB_TOKEN
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::252078852689:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: 252078852689.dkr.ecr.us-west-2.amazonaws.com
          ECR_REPOSITORY: eva-test
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          git config --local user.email shinekumar23@gmail.com
          git config --local user.name shinekumar23
          git checkout main
          git pull origin main 
          sed -i "s/eva-test:[0-9]\+$/eva-test:$IMAGE_TAG/" deployment/dev/deployment.yaml
          git commit -a -m "Updated version tag"
          git push origin main
          aws eks update-kubeconfig --region us-west-2 --name test-eva
          kubectl get ns

