name: Restore database

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: Workflow Run
        default: Restore
        required: true

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
      id: build
      with:
          fetch-depth: 0
    - name: Build the Docker image
      env:
        ENVIRONMENT: ${{ vars.DEV_ENVIRNMENT }}
        DB_HOST: ${{ vars.DEV_DB_HOST }}
        DB_USERNAME: ${{ vars.DEV_DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        DB_DATABASE: ${{ vars.DEV_DB_DATABASE }}
        NODE_ENV: ${{ secrets.DEV_NODE_ENV }}
        AWS_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.DEV_AWS_SECRET_KEY }}
        ECR_REPO_URL: ${{ vars.DEV_ECR_REPO_URL }}
        ECR_REPO_NAME: ${{ vars.DEV_ECR_REPO_NAME }}
        REGION: ${{ vars.REGION }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        GIT_USER_USERNAME: ${{ secrets.GIT_USER_USERNAME }}


      if: github.event.inputs.version == 'Restore'
      run: |
        echo "Hello"
        aws s3 cp s3://cognianextgen-rds-backup/data.sql . --region us-east-2
        PGPASSWORD=Agb09hbs2 pg_dump -h cognianxtgen.cluster-cpdaobpdl4ur.us-east-2.rds.amazonaws.com -U cognianxtgenuser -d cognianxtgendb -f backup.sql
        # Check if the dump command was successful (exit status 0)
        if [ $? -eq 0 ]; then
            echo "Dump command executed successfully"
            
            # Perform the restore command
            PGPASSWORD=Agb09hbs2 pg_restore -h cognianxtgen.cluster-cpdaobpdl4ur.us-east-2.rds.amazonaws.com -U cognianxtgenuser -d cognianxtgendb data.sql
            
            # Check if the restore command was successful (exit status 0)
            if [ $? -eq 0 ]; then
                echo "Restore command executed successfully"
                aws s3 cp backup.sql s3://cognianextgen-rds-backup/backup/
            else
                echo "Restore command failed"
            fi
        else
            echo "Dump command failed"
        fi
